name: CI workflow

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -V
